Fix _corrupt_signing_params() in Apollo BFT client
_corrupt_signing_params corrupts signatures by incrementing a random
position of the buffer with one. However if the value to be incremented
is 255 an error occurs, because it can't be translated to byte array.

E.g.:
 File "/concord-bft/util/pyclient/bft_client.py", line 372, in _corrupt_signing_params
1698
    signature = bytes(signature[0:pos]) + bytes([val]) + bytes(signature[pos+1:])
1699
ValueError: bytes must be in range(0, 256)