Fix unused return value warning in FileStorage
The following was found during a release build using GCC.

```
/home/andrewstone/concord-bft/bftengine/tests/simpleStorage/FileStorage.cpp: In member function ‘virtual bool bftEngine::FileStorage::initMaxSizeOfObjects(bftEngine::MetadataStorage::ObjectDesc*, uint32_t)’:
/home/andrewstone/concord-bft/bftengine/tests/simpleStorage/FileStorage.cpp:136:12: error: ignoring return value of ‘int ftruncate(int, __off_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
   ftruncate(fileno(dataStream_), maxFileSize);
   ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
```