Rename Assert* to ConcordAssert*
Reason:
The name `Assert` is not unique and conflicts Google Test:
```
/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:295:36: error: too many arguments provided to function-like macro invocation
inline void Assert(bool condition, const char* file, int line,
```
Using `#undef` seems to be tricky.