fix type errors logged by gcc 7
When moving from gcc 6 to gcc 7, warnings of this sort were logged for these sites:

```
In file included from /concord/submodules/concord-bft/threshsign/src/bls/relic/BlsMultisigVerifier.cpp:22:0:
concord-bft/threshsign/src/bls/relic/BlsMultisigVerifier.cpp: In constructor 'BLS::Relic::BlsMultisigVerifier::BlsMultisigVerifier(const BLS::Relic::BlsPublicParameters&, NumSharesType, NumSharesType, const std::vector<BLS::Relic::BlsPublicKey>&)':
concord-bft/threshsign/src/bls/relic/BlsMultisigVerifier.cpp:32:35: error: conversion to 'std::vector<BLS::Relic::BlsPublicKey>::size_type {aka long unsigned int}' from 'NumSharesType {aka int}' may change the sign of the result [-Werror=sign-conversion]
     assertEqual(verifKeys.size(), static_cast<size_t>(numSigners + 1));
concord-bft/threshsign/src/bls/relic/../../XAssert.h:95:20: note: in definition of macro 'XASSERT_Equal'
     if((first) != (second)) { \
                    ^~~~~~
concord-bft/threshsign/src/bls/relic/BlsMultisigVerifier.cpp:32:5: note: in expansion of macro 'assertEqual'
     assertEqual(verifKeys.size(), static_cast<size_t>(numSigners + 1));
     ^~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

This change matches the cast type to the comparison type, to clear up the error.